funcoes = ["dar bom dia",
            "dizer de nada",
            "dizer quem é o CEO do sexo",
            "dizer quando será lançado o Sexo 2",
            "contar piadas",
            "dar a definição de gay",
            "dar a definição de lésbica",
            "dar a definição de bi",
            "ajudar a conquistar uma casada",
            "ajudar a conseguir uma namorada",
            "oferecer ajuda",
            "dizer a versão atual",
            "gerar senhas"]